/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlttnn.GUI;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import qlttnn.BLL.ketquathiBLL;
import qlttnn.DTO.ketquathiDTO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.AEADBadTagException;
import javax.swing.JOptionPane;
import qlttnn.BLL.danhsachphongthiBUS;
import qlttnn.DTO.danhsachphongthiDTO;
/**
 *
 * @author ADMIN
 */
public class danhsachthisinhSuggest extends javax.swing.JDialog {
DefaultTableModel table;
    danhsachphongthiBUS bus = new  danhsachphongthiBUS();
 private String maphthi,trinhdo;
    /**
     * Creates new form danhsachthisinhSuggest
     */
    public danhsachthisinhSuggest(String maphthi, String trinhdo) {  

        this.maphthi = maphthi;
        this.trinhdo = trinhdo;
        initComponents();
        data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTSID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnghe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtviet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtSBD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtnoi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdoc = new javax.swing.JTextField();
        Thembtn = new javax.swing.JButton();
        txtMaphongthi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnsuggest = new javax.swing.JButton();
        txtstt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(646, 711));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("DANH SÁCH THÍ SINH PHÒNG THI");

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setText("Mã thí sinh");

        txtTSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTSIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Đọc");

        txtnghe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngheActionPerformed(evt);
            }
        });

        jLabel5.setText("Nghe");

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thí sinh", "Mã phòng thi", "SBD", "Nghe", "Nói", "Đọc ", "Viết", "STT"
            }
        ));
        jt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt);

        jLabel9.setText("Nói");

        txtSBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSBDActionPerformed(evt);
            }
        });

        jLabel10.setText("Số Báo Danh ");

        txtnoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoiActionPerformed(evt);
            }
        });

        jLabel4.setText("Viết");

        Thembtn.setText("Thêm thí sinh");
        Thembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThembtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã phòng thi");

        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnsuggest.setText("...");
        btnsuggest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuggestActionPerformed(evt);
            }
        });

        jLabel6.setText("STT");

        jButton1.setText("Reload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtviet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdoc)
                            .addComponent(txtnoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnghe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Thembtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtstt))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTSID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsuggest, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaphongthi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSBD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtMaphongthi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btnsuggest))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtdoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtviet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Thembtn)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTSIDActionPerformed

    private void txtngheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngheActionPerformed

    private void jtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMouseClicked
        // TODO add your handling code here:
        int i = jt.getSelectedRow();
        if (i >= 0)
        setTextFields(jt.getValueAt(i, 0).toString(), jt.getValueAt(i, 1).toString(), jt.getValueAt(i, 2).toString(), jt.getValueAt(i, 3).toString(), jt.getValueAt(i, 4).toString(), jt.getValueAt(i, 5).toString(), jt.getValueAt(i, 6).toString(),jt.getValueAt(i, 7).toString());
    }//GEN-LAST:event_jtMouseClicked

    private void txtSBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSBDActionPerformed

    private void txtnoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoiActionPerformed

    private void ThembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThembtnActionPerformed
        danhsachphongthiBUS bus = new danhsachphongthiBUS();
       txtstt.setText(bus.remindSTT());
        qlttnn.DTO.danhsachphongthiDTO gt = new qlttnn.DTO.danhsachphongthiDTO();
        gt.setTsID(Integer.parseInt(txtTSID.getText()));
        gt.setPhongthiID(Integer.parseInt(maphthi));
        gt.setSbd(trinhdo+txtstt.getText());
         gt.setNghe(Float.parseFloat(txtnghe.getText()));
          gt.setNoi(Float.parseFloat(txtdoc.getText()));
           gt.setDoc(Float.parseFloat(txtdoc.getText()));
            gt.setViet(Float.parseFloat(txtviet.getText()));
            gt.setStt(Integer.parseInt(txtstt.getText()));
       
       

        Vector head = new Vector();
        head.add(gt.getTsID());
        head.add(gt.getPhongthiID());
           head.add(gt.getSbd());
              head.add(gt.getNghe());   head.add(gt.getNoi());
                 head.add(gt.getDoc());
                    head.add(gt.getViet());
                       head.add(gt.getStt());
                 
              
              
              
       ;
  

        int rs = bus.them(gt);
        if(rs == 1){
            table.addRow(head);
            jt.setModel(table);
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        }else{
            JOptionPane.showMessageDialog(null, "Mã đã tồn tại. Thêm thất bại");
        }
        cleanView();
    }//GEN-LAST:event_ThembtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnsuggestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuggestActionPerformed
if(evt.getSource()==btnsuggest){ // Suggest tour
            thisinhSuggest td = new thisinhSuggest();
            td.setVisible(true);
            String s = td.getTextFieldContent();
            txtTSID.setText(s);
        }       
    }//GEN-LAST:event_btnsuggestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cleanView();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void setTextFields(String toString, String toString0, String toString1, String toString2, String toString3, String toString4, String toString5,String toString6) {
        txtTSID.setText(toString);
         txtMaphongthi.setText(toString0);
          txtSBD.setText(toString1);
        txtnghe.setText(toString2);
        txtnoi.setText(toString3);
        txtdoc.setText(toString4);
         txtviet.setText(toString5);
         txtstt.setText(toString6);
       
        
       
       
    }
    public void doDuLieuSearch(Map<String,String> map)
    {
         danhsachphongthiBUS bus = new danhsachphongthiBUS();
        try {
            bus.docduLieumaphong(map);
             table = (DefaultTableModel) jt.getModel();
            //////////////arraylists
            table.setRowCount(0);
                  table.setRowCount(0);
       for (qlttnn.DTO.danhsachphongthiDTO kh : bus.ds) {
           Vector vt = new Vector();
           vt.add(kh.getTsID());
           vt.add(kh.getPhongthiID());
           vt.add(kh.getSbd());
           vt.add(kh.getNghe());
           vt.add(kh.getNoi());
           vt.add(kh.getDoc());
           vt.add(kh.getViet());
           vt.add(kh.getStt());
           table.addRow(vt);
       }
        jt.setModel(table);
       
        } catch (Exception ex) {
            Logger.getLogger(danhsachphongthiDTO.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    public void data(){
        Map<String,String> map = new HashMap<>();
       map.put("maphongthi",maphthi.toString());
        doDuLieuSearch(map);
    }
//    public void list(){
//   try {
//       if(bus.getList() == null)
//           bus.docDuLieu();
//       
//      
//       int a = Integer.parseInt(maphthi);
//       System.out.println();
//       List<danhsachphongthiDTO> kq = bus.getListKQ(a);
//       table = (DefaultTableModel) jt.getModel();
//       table.setRowCount(0);
//       for (qlttnn.DTO.danhsachphongthiDTO kh : bus.ds) {
//           Vector vt = new Vector();
//           vt.add(kh.getTsID());
//           vt.add(kh.getPhongthiID());
//           vt.add(kh.getSbd());
//           vt.add(kh.getNghe());
//           vt.add(kh.getNoi());
//           vt.add(kh.getDoc());
//           vt.add(kh.getViet());
//           vt.add(kh.getStt());
//           table.addRow(vt);
//       }
//       jt.setModel(table);
//       
//       
//   } catch (Exception ex) {
//         Logger.getLogger(chitietketquathiSuggest.class.getName()).log(Level.SEVERE, null, ex);
//  // Handle the condition when str is not a number.
//}
        
        
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Thembtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnsuggest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    private javax.swing.JTextField txtMaphongthi;
    private javax.swing.JTextField txtSBD;
    private javax.swing.JTextField txtTSID;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtnghe;
    private javax.swing.JTextField txtnoi;
    private javax.swing.JTextField txtstt;
    private javax.swing.JTextField txtviet;
    // End of variables declaration//GEN-END:variables
public void cleanView() //Xóa trắng các TextField
    {
        txtTSID.setText("");
        txtMaphongthi.setText("");
         txtSBD.setText("");
          txtnghe.setText("");
           txtnoi.setText("");
            txtdoc.setText("");
           txtviet.setText("");
         txtstt.setText("");
      
       

    }}
