/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlttnn.GUI;


import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlttnn.BLL.phongthiBLL;
import qlttnn.DTO.phongthiDTO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ADMIN
 */
public class phongthiGUI extends javax.swing.JPanel {
DefaultTableModel table;
    /**
     * Creates new form phongthiGUI
     */
    public phongthiGUI() {
        initComponents();
        doDuLieuLenBang();
        txtMaphong.setEditable(false);
        txttenphong.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtMaphong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txttenphong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        txtkhoathi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtcathi = new javax.swing.JTextField();
        btnsugestcathi = new javax.swing.JButton();
        btnsuggestkhoathi = new javax.swing.JButton();
        trinhdotxt = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        soluongtxt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnds = new javax.swing.JButton();
        btnthemdspt = new javax.swing.JButton();

        jPanel10.setBackground(new java.awt.Color(153, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(646, 711));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 204));
        jLabel7.setText("QUẢN LÝ KHÓA THI");

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        jLabel8.setText("Mã phòng thi");

        txtMaphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaphongActionPerformed(evt);
            }
        });

        jLabel9.setText("Tên phòng thi");

        txttenphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenphongActionPerformed(evt);
            }
        });

        jLabel10.setText("Ca thi");

        btnThem.setText("Tạo mới");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phòng thi", "Tên phòng thi", "Ca thi", "Khóa thi", "Trình độ", "Số lượng"
            }
        ));
        jt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt);

        jLabel1.setText("Khóa thi");

        btnsugestcathi.setText("...");
        btnsugestcathi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsugestcathiActionPerformed(evt);
            }
        });

        btnsuggestkhoathi.setText("...");
        btnsuggestkhoathi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuggestkhoathiActionPerformed(evt);
            }
        });

        trinhdotxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A2", "B1" }));
        trinhdotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trinhdotxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Trình độ");

        soluongtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "31", "32", "33", "34", "35" }));

        jLabel3.setText("Số lượng");

        btnds.setText("Danh sách phòng thi");
        btnds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndsActionPerformed(evt);
            }
        });

        btnthemdspt.setText("Tạo danh sách");
        btnthemdspt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemdsptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttenphong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtcathi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsugestcathi))
                            .addComponent(soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtkhoathi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsuggestkhoathi)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trinhdotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnds)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnthemdspt)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txttenphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtcathi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsugestcathi))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkhoathi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnsuggestkhoathi)
                    .addComponent(trinhdotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnds)
                    .addComponent(btnthemdspt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaphongActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
       phongthiBLL bus = new phongthiBLL();
        txtMaphong.setText(bus.remindThisinhID());
        qlttnn.DTO.phongthiDTO gt = new qlttnn.DTO.phongthiDTO();
        gt.setPhongthiID(Integer.parseInt(txtMaphong.getText()));
        gt.setTenphongthi(trinhdotxt.getSelectedItem().toString()+"P"+ txtMaphong.getText());
        gt.setCathiID(Integer.parseInt(txtcathi.getText()));
        gt.setKhoathiID(Integer.parseInt(txtkhoathi.getText()));
        gt.setTrinhdo(trinhdotxt.getSelectedItem().toString());
        gt.setSoluong(Integer.parseInt(soluongtxt.getSelectedItem().toString()));

        Vector head = new Vector();
        head.add(gt.getPhongthiID());
            head.add(gt.getTenphongthi());
            head.add(gt.getCathiID()); 
            head.add(gt.getKhoathiID());
            head.add(gt.getTrinhdo());
            head.add(gt.getSoluong());
       
      
       

        int rs = bus.them(gt);
        if(rs == 1){
            table.addRow(head);
            jt.setModel(table);
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        }else{
            JOptionPane.showMessageDialog(null, "Mã đã tồn tại. Thêm thất bại");
        }
        cleanView();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void jtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMouseClicked

        // TODO add your handling code here:
        int i = jt.getSelectedRow();
        if (i >= 0)

        setTextFields(jt.getValueAt(i, 0).toString(), jt.getValueAt(i, 1).toString(), 
                jt.getValueAt(i, 2).toString(), jt.getValueAt(i, 3).toString(), 
                jt.getValueAt(i, 4).toString(), jt.getValueAt(i, 5).toString());

    }//GEN-LAST:event_jtMouseClicked

    private void btnsugestcathiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsugestcathiActionPerformed
      if(evt.getSource()== btnsugestcathi){ // Suggest tour
            CathiSuggest td = new CathiSuggest();
            td.setVisible(true);
            String s = td.getTextFieldContent();
            txtcathi.setText(s);
        }
    }//GEN-LAST:event_btnsugestcathiActionPerformed

    private void btnsuggestkhoathiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuggestkhoathiActionPerformed
         if(evt.getSource()== btnsuggestkhoathi){ // Suggest tour
            khoathiSuggest td = new khoathiSuggest();
            td.setVisible(true);
            String s = td.getTextFieldContent();
            txtkhoathi.setText(s);
        }
    }//GEN-LAST:event_btnsuggestkhoathiActionPerformed

    private void btndsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndsActionPerformed
    chitietketquathiSuggest ct = new chitietketquathiSuggest(txtMaphong.getText());
        ct.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btndsActionPerformed

    private void btnthemdsptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemdsptActionPerformed
       danhsachthisinhSuggest dspt = new danhsachthisinhSuggest(txtMaphong.getText(),trinhdotxt.getSelectedItem().toString());
       dspt.setVisible(true);
    }//GEN-LAST:event_btnthemdsptActionPerformed

    private void txttenphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenphongActionPerformed

    private void trinhdotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trinhdotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trinhdotxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnds;
    private javax.swing.JButton btnsugestcathi;
    private javax.swing.JButton btnsuggestkhoathi;
    private javax.swing.JButton btnthemdspt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    private javax.swing.JComboBox<String> soluongtxt;
    private javax.swing.JComboBox<String> trinhdotxt;
    private javax.swing.JTextField txtMaphong;
    private javax.swing.JTextField txtcathi;
    private javax.swing.JTextField txtkhoathi;
    private javax.swing.JTextField txttenphong;
    // End of variables declaration//GEN-END:variables
private void setTextFields(String toString, String toString0,String toString1,String toString2,String toString3,String toString4)  {
      txtMaphong.setText(toString);
       txttenphong.setText(toString0);
        txtcathi.setText(toString1);
      txtkhoathi.setText(toString2);
      trinhdotxt.setSelectedItem(toString3);
      soluongtxt.setSelectedItem(toString4);
      
        

        
    }

    public void doDuLieuLenBang() {
        phongthiBLL bus = new phongthiBLL();
        try {
            bus.docDuLieu();
            table = (DefaultTableModel) jt.getModel();
            table.setRowCount(0);
            for (qlttnn.DTO.phongthiDTO kh : bus.ds) {
                Vector vt = new Vector();
                vt.add(kh.getPhongthiID());
               vt.add(kh.getTenphongthi());
               vt.add(kh.getCathiID());
               vt.add(kh.getKhoathiID());
               
                vt.add(kh.getTrinhdo());
                vt.add(kh.getSoluong());
             
                
               
                table.addRow(vt);
            }
            jt.setModel(table);
        } catch (Exception ex) {
            Logger.getLogger(phongthiDTO.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void cleanView() //Xóa trắng các TextField
    {
        txtMaphong.setText("");
        txttenphong.setText("");
           txtcathi.setText("");
              txtkhoathi.setText("");
    }
              
           
      
    }
